#23 How to find the length of a string?

from typing import Counter


userstring=input("enter string ") 

########################################

# print(f'string is {userstring}  & length of string is {len(userstring)}')

#########################################

# counter=0
# for i in userstring:
#     counter += 1
# print(counter)     

##########################################

# counter=0
# while userstring[counter:]:
#     counter += 1
# print(counter)

##########################################

# def len_userstr ():
#     print(len(userstring))

# len_userstr()

##########################################

# def len_userstr(userstring):
#     counter=0
#     for i in userstring:
#         counter+=1
#     return counter
# print(len_userstr(userstring))

###########################################

# def len_userstr(userstring):
#     counter=0
#     while userstring[counter:]:
#         counter+=1
#     return counter
# print(len_userstr(userstring))

###########################################